base_url: "https://hackaprompt.com/track/tutorial_competition/getting_started"

challenge_specific_configs:
  getting_started:
    # Selectors for the "Getting Started" challenge
    # We will need to inspect the page to get these accurately
    prompt_textarea: "textarea[data-testid='multimodal-input']"
    submit_prompt_button: "button[data-testid='send-button']" # Renamed for clarity
    submit_for_judging_button: "button:has-text('Submit Current Response For Judging')"
    new_attempt_button: "button:has-text('Start a New Attempt')"
    # Example of what a success/failure indicator might look like - needs inspection
    # response_area: "div.chat-response-area" 
    # success_indicator_text: "Your prompt was successful"
    # failure_indicator_text: "The model refused to respond"

    # Prompts to try for this challenge
    prompts:
      - id: interaction_test_1
        text: "Testing basic interactions."
        # expected_outcome: "buttons_clickable" # We'll handle this in the script logic

# We can add more challenges here later, e.g.:
# another_challenge:
#   prompt_textarea: "some_other_selector"
#   submit_button: "yet_another_selector"
#   prompts: [...] 