base_url: "https://www.hackaprompt.com/track/pliny/pliny_4_challenge"

# General automation settings
automation_settings:
  browser_executable_path: "brave-browser-beta"
  user_data_dir: "/tmp/brave-automation"
  remote_debugging_port: 9222
  browser_ws_endpoint: "http://localhost:9222"
  navigate_to_base_url: false
  loop_on_failure: true
  max_retries: 100
  random_delay: true
  delay_min_sec: 7
  delay_max_sec: 30

# Page element selectors for the challenge
selectors:
  # These selectors will need to be verified by inspecting the page
  prompt_textarea: "textarea[data-testid='multimodal-input']"
  submit_prompt_button: "button[data-testid='send-button']"
  submit_for_judging_button: "button:has-text('Submit Current Response For Judging')"
  new_attempt_button: "button:has-text('Start a New Attempt')"
  # Example success/failure indicators (needs inspection)
  # response_area: "div.chat-response-area"
  # success_indicator_text: "Your prompt was successful"
  # failure_indicator_text: "The model refused to respond"

# Prompts to try for the challenge
prompts:
  - file: "prompts/prompt_1.txt"
    # The script logic will handle the expected outcome, e.g., "buttons_clickable"

# Browser cleanup configuration
cleanup:
  # Set to false to disable automatic cleanup (recommended for manual browser management)
  enabled: false
  
  # Never close browser automatically, even on script errors or completion
  never_auto_close: true
  
  # Inactivity timeout before auto-cleanup (only used if enabled: true)
  inactivity_timeout:
    hours: 1
    minutes: 30
  
  # Whether to close individual tabs or the entire browser instance
  close_mode: "instance"  # Options: "tabs" or "instance"
  
  # Grace period after automation completion before starting inactivity monitoring
  grace_period_minutes: 5