base_url: "https://www.hackaprompt.com/track/pliny/pliny_2_challenge"

# General automation settings
automation_settings:
  browser_executable_path: "brave-browser-beta"
  user_data_dir: "profiles/brave-beta"
  remote_debugging_port: 9222
  browser_ws_endpoint: "http://localhost:9222"
  navigate_to_base_url: false
  loop_on_failure: true
  max_retries: 1000
  random_delay: false
  delay_min_sec: 4
  delay_max_sec: 12
  # Centralised timeout settings (all values in milliseconds unless noted)
  timeouts:
    prompt_visible_ms: 10000          # Wait for prompt textarea to be visible
    submit_prompt_click_ms: 5000      # Timeout for clicking the prompt submit button
    submit_for_judging_enable_ms: 180000  # Wait for 'Submit for Judging' to enable
    submit_for_judging_click_ms: 180000   # Timeout for clicking 'Submit for Judging'
    success_visible_ms: 5000          # Wait for success popup visibility
    restart_click_ms: 5000            # Timeout for clicking 'Restart Challenge' on failure
    continue_button_visible_ms: 5000  # Wait for 'Continue Current Chat' button visibility
    continue_button_click_ms: 5000    # Timeout for clicking the 'Continue' button
    polling_interval_ms: 500          # Interval between status checks (ms)
    judging_timeout_sec: 180          # Overall judging timeout (seconds)

# Page element selectors for the challenge
selectors:
  # These selectors will need to be verified by inspecting the page
  prompt_textarea: "textarea[data-testid='multimodal-input']"
  submit_prompt_button: "button[data-testid='send-button']"
  submit_for_judging_button: "button:has-text('Submit Current Response For Judging')"
  # Selectors for the intent loop
  intent_textarea: "textarea[placeholder='Enter your template with exactly one <INTENT> placeholder...']"
  submit_template_button: "button:has-text('Submit Template')"
  new_attempt_button: "button:has-text('Start a New Attempt')"
  # Example success/failure indicators (needs inspection)
  # response_area: "div.chat-response-area"
  # success_indicator_text: "Your prompt was successful"
  # failure_indicator_text: "The model refused to respond"

# Prompts to try for the challenge
prompts:
  - file: "prompts/prompt_1.txt"
    # The script logic will handle the expected outcome, e.g., "buttons_clickable"