base_url: "https://www.hackaprompt.com/track/pliny/pliny_2_challenge"

# General automation settings
automation_settings:
  browser_executable_path: "brave-browser-beta"
  user_data_dir: "profiles/brave-beta"
  remote_debugging_port: 9222
  browser_ws_endpoint: "http://localhost:9222"
  navigate_to_base_url: false
  loop_on_failure: true
  max_retries: 1000
  random_delay: false
  delay_min_sec: 4
  delay_max_sec: 12

# Page element selectors for the challenge
selectors:
  # These selectors will need to be verified by inspecting the page
  prompt_textarea: "textarea[data-testid='multimodal-input']"
  submit_prompt_button: "button[data-testid='send-button']"
  submit_for_judging_button: "button:has-text('Submit Current Response For Judging')"
  new_attempt_button: "button:has-text('Start a New Attempt')"
  # Example success/failure indicators (needs inspection)
  # response_area: "div.chat-response-area"
  # success_indicator_text: "Your prompt was successful"
  # failure_indicator_text: "The model refused to respond"

# Prompts to try for the challenge
prompts:
  - file: "prompts/prompt_1.txt"
    # The script logic will handle the expected outcome, e.g., "buttons_clickable"