base_url: "https://www.hackaprompt.com/track/pliny/pliny_4_challenge"

# General automation settings
automation_settings:
  browser_executable_path: "brave-browser-beta"
  user_data_dir: "/tmp/brave-automation"
  remote_debugging_port: 9222
  browser_ws_endpoint: "http://localhost:9222"
  navigate_to_base_url: false
  loop_on_failure: true
  max_retries: 3
  random_delay: false
  delay_min_sec: 5
  delay_max_sec: 60

challenge_specific_configs:
  getting_started:
    # Selectors for the "Getting Started" challenge
    # We will need to inspect the page to get these accurately
    prompt_textarea: "textarea[data-testid='multimodal-input']"
    submit_prompt_button: "button[data-testid='send-button']" # Renamed for clarity
    submit_for_judging_button: "button:has-text('Submit Current Response For Judging')"
    new_attempt_button: "button:has-text('Start a New Attempt')"
    # Example of what a success/failure indicator might look like - needs inspection
    # response_area: "div.chat-response-area" 
    # success_indicator_text: "Your prompt was successful"
    # failure_indicator_text: "The model refused to respond"

    # Prompts to try for this challenge
    prompts:
      - id: interaction_test_1
        file: "prompts/getting_started_prompt.txt"
        # expected_outcome: "buttons_clickable" # We'll handle this in the script logic

# We can add more challenges here later, e.g.:
# another_challenge:
#   prompt_textarea: "some_other_selector"
#   submit_button: "yet_another_selector"
#   prompts: [...] 












# Browser cleanup configuration
cleanup:
  # Set to false to disable automatic cleanup (recommended - you manage the browser yourself)
  enabled: false
  
  # Never close browser automatically, even on script errors or completion
  never_auto_close: true
  
  # Inactivity timeout before auto-cleanup (only used if enabled: true)
  inactivity_timeout:
    hours: 1
    minutes: 30
  
  # Whether to close individual tabs or the entire browser instance
  close_mode: "instance"  # Options: "tabs" or "instance"
  
  # Grace period after automation completion before starting inactivity monitoring
  grace_period_minutes: 5