base_url: "https://hackaprompt.com/track/tutorial_competition/getting_started"

# General automation settings
automation_settings:
  loop_on_failure: true
  random_delay: true
  delay_min_sec: 5
  delay_max_sec: 60

challenge_specific_configs:
  getting_started:
    # Selectors for the "Getting Started" challenge
    # We will need to inspect the page to get these accurately
    prompt_textarea: "textarea[data-testid='multimodal-input']"
    submit_prompt_button: "button[data-testid='send-button']" # Renamed for clarity
    submit_for_judging_button: "button:has-text('Submit Current Response For Judging')"
    new_attempt_button: "button:has-text('Start a New Attempt')"
    # Example of what a success/failure indicator might look like - needs inspection
    # response_area: "div.chat-response-area" 
    # success_indicator_text: "Your prompt was successful"
    # failure_indicator_text: "The model refused to respond"

    # Prompts to try for this challenge.
    # You can either provide the text directly or point to a file.
    prompts:
      - id: prompt_from_text
        text: "This is a simple prompt directly in the yaml."
      - id: prompt_from_file
        file: "prompts/example_prompt.txt" # Path is relative to the project root

# We can add more challenges here later, e.g.:
# another_challenge:
#   prompt_textarea: "some_other_selector"
#   submit_button: "yet_another_selector"
#   prompts: [...] 












# Browser cleanup configuration
cleanup:
  # Set to false to disable automatic cleanup (recommended - you manage the browser yourself)
  enabled: false
  
  # Never close browser automatically, even on script errors or completion
  never_auto_close: true
  
  # Inactivity timeout before auto-cleanup (only used if enabled: true)
  inactivity_timeout:
    hours: 1
    minutes: 30
  
  # Whether to close individual tabs or the entire browser instance
  close_mode: "instance"  # Options: "tabs" or "instance"
  
  # Grace period after automation completion before starting inactivity monitoring
  grace_period_minutes: 5