base_url: "https://www.hackaprompt.com/track/pliny/pliny_2_challenge"

# General automation settings
automation_settings:
  browser_executable_path: "brave-browser-beta"
  user_data_dir: "profiles/brave-beta"
  remote_debugging_port: 9222
  browser_ws_endpoint: "http://localhost:9222"
  navigate_to_base_url: false
  loop_on_failure: true
  # Wait time (seconds) for the browser to fully launch before connecting
  browser_init_wait_sec: 5

  # Centralised timeout settings (all values in milliseconds unless noted)
  timeouts:
    prompt_visible_ms: 10000          # Wait for prompt textarea to be visible
    submit_prompt_click_ms: 5000      # Timeout for clicking the prompt submit button
    submit_for_judging_enable_ms: 180000  # Wait for 'Submit for Judging' to enable
    submit_for_judging_click_ms: 180000   # Timeout for clicking 'Submit for Judging'
    success_visible_ms: 5000          # Wait for success popup visibility
    restart_click_ms: 5000            # Timeout for clicking 'Restart Challenge' on failure
    continue_button_visible_ms: 5000  # Wait for 'Continue Current Chat' button visibility
    continue_button_click_ms: 5000    # Timeout for clicking the 'Continue' button
    polling_interval_ms: 500          # Interval between status checks (ms)
    judging_timeout_sec: 180          # Overall judging timeout (seconds)

# Task-specific configuration files
task_configs:
  agent_track_submit: "../cbrne/agent_track_submit_config.yaml"

# Browser cleanup and monitoring settings
cleanup:
  enabled: false            # Set true if you want automatic cleanup after inactivity
  inactivity_timeout:
    hours: 1
    minutes: 30
  grace_period_minutes: 5   # Wait after automation finishes before monitoring starts
  check_interval_sec: 30    # Interval between browser activity checks

# Prompts to try for the challenge
prompts:
  - file: "prompts/prompt_1.txt"
    # The script logic will handle the expected outcome, e.g., "buttons_clickable"