# Example configuration showing how to enable the refresh feature
# Copy these settings to your main config.yaml file

base_url: "https://www.hackaprompt.com/track/pliny/pliny_2_challenge"

# Agent track submit specific configuration
agent_track_submit:
  # Retry settings
  retry_settings:
    max_retries: 1000
    delay_min_sec: 4
    delay_max_sec: 12
    random_delay: false
    refresh_on_timeout: true      # Enable refresh feature
    refresh_timeout_sec: 30      # Wait 30 seconds before refreshing
  
  # Timeout settings (in milliseconds unless noted)
  timeouts:
    prompt_visible_ms: 10000
    submit_prompt_click_ms: 5000
    submit_template_enable_ms: 180000
    try_again_button_visible_ms: 90000
    try_again_button_click_ms: 5000
    polling_interval_ms: 200
    enable_wait_fallback_ms: 30000
  
  # CSS selectors
  selectors:
    textarea: "textarea"
    submit_button: 'button:has-text("Submit Template")'
    try_again_button: 'button:has-text("Try Again")'
  
  # Logging messages
  logging:
    filling_textarea: "Filling intent textarea for agent-track-submit"
    waiting_submit_button: "Waiting for 'Submit Template' button to enable, then clicking"
    button_timeout_warning: "'Submit Template' button did not enable within timeout; attempting click anyway"
    starting_attempt: "Starting attempt {attempt}/{max_retries}"
    waiting_try_again: "Waiting for 'Try Again' button to appear"
    refresh_timeout_reached: "Refresh timeout reached, refreshing page instead of waiting for Try Again button"
    page_refreshed: "Page refreshed successfully, continuing with next attempt"
    reached_max_retries: "Reached maximum retries ({max_retries}). Stopping."
    clicking_try_again: "Clicking 'Try Again' button (attempt {attempt})"
    waiting_before_next: "Waiting {delay:.2f} seconds before next attempt"
    error_during_attempt: "Error during attempt {attempt}: {error}"
    error_max_retries: "Reached maximum retries ({max_retries}). Stopping due to error."
    waiting_after_error: "Waiting {delay:.2f} seconds before retrying after error"
    completed_retry: "Completed agent_track_submit_with_retry after {attempts} attempts"
