base_url: "https://www.hackaprompt.com/track/trails_x_mats/robust_rewording"

# General automation settings
automation_settings:
  browser_executable_path: "brave-browser-beta"
  user_data_dir: "profiles/brave-beta"
  remote_debugging_port: 9222
  browser_ws_endpoint: "http://localhost:9222"
  navigate_to_base_url: false
  loop_on_failure: true
  # Wait time (seconds) for the browser to fully launch before connecting
  browser_init_wait_sec: 5

  # Centralised timeout settings (all values in milliseconds unless noted)
  timeouts:
    prompt_visible_ms: 1000          # Wait for prompt textarea to be visible
    submit_prompt_click_ms: 2000      # Timeout for clicking the prompt submit button
    submit_for_judging_enable_ms: 180000  # Wait for 'Submit for Judging' to enable
    submit_for_judging_click_ms: 180000   # Timeout for clicking 'Submit for Judging'
    success_visible_ms: 5000          # Wait for success popup visibility
    restart_click_ms: 5000            # Timeout for clicking 'Restart Challenge' on failure
    continue_button_visible_ms: 5000  # Wait for 'Continue Current Chat' button visibility
    continue_button_click_ms: 5000    # Timeout for clicking the 'Continue' button
    polling_interval_ms: 500          # Interval between status checks (ms)
    judging_timeout_sec: 180          # Overall judging timeout (seconds)

# Agent track submit specific configuration
agent_track_submit:
  retry_settings:
    max_retries: 50
    delay_min_sec: 1
    delay_max_sec: 5
    random_delay: false
    refresh_on_timeout: false
    refresh_timeout_sec: 200
  
  timeouts:
    prompt_visible_ms: 10000
    submit_prompt_click_ms: 5000
    submit_template_enable_ms: 30000
    try_again_button_visible_ms: 15000
    try_again_button_click_ms: 3000
    post_refresh_wait_ms: 2000
    dropdown_open_ms: 300
    dropdown_item_click_ms: 300
    polling_interval_ms: 200
    enable_wait_fallback_ms: 30000
    # Dropdown specific waits
    dropdown_aria_expanded_poll_ms: 100
    dropdown_aria_expanded_max_checks: 20
    post_selection_wait_ms: 100

  # Flags to control optional waits (set true to skip/short-circuit waits)
  flags:
    skip_post_selection_wait: true
    skip_submit_enable_wait: true
    skip_wait_try_again_visible: true
    fast_dropdown: true
  
  selectors:
    textarea: 'textarea'
    submit_button: 'button:has-text("Submit Template")'
    try_again_button: 'button:has-text("Try Again")'
    dropdown_button: 'button[aria-haspopup="menu"][data-state="closed"]:not([data-testid="user-menu-trigger"])'
    dropdown_menu: 'div[role="menu"]'
    model_item: 'div[role="menuitem"]:has-text("{model_name}")'
    # Fallback selectors tried in order if dropdown_button is not found
    dropdown_button_fallbacks:
      - 'button:has(svg.lucide-bot):has(svg.lucide-chevron-down):not([data-testid="user-menu-trigger"])'
      - 'button[aria-haspopup="menu"]:not([data-testid="user-menu-trigger"])'
  
  logging:
    starting_attempt: "Starting attempt {attempt}/{max_retries}"
    selecting_model: "Selecting model: {model_name}"
    found_dropdown_button: "Found dropdown button: {preview}"
    model_selected: "Successfully selected model: {model_name}"
    model_selection_error: "Error selecting model {model_name}: {error}"
    filling_textarea: "Filling intent textarea for agent-track-submit"
    waiting_submit_button: "Waiting for 'Submit Template' button to enable, then clicking"
    button_timeout_warning: "'Submit Template' button did not enable within timeout; attempting click anyway"
    waiting_try_again: "Waiting for 'Try Again' button to appear"
    refresh_timeout_reached: "Refresh timeout reached, refreshing page instead of waiting for Try Again button"
    page_refreshed: "Page refreshed successfully, continuing with next attempt"
    reached_max_retries: "Reached maximum retries ({max_retries}). Stopping."
    clicking_try_again: "Clicking 'Try Again' button (attempt {attempt})"
    waiting_before_next: "Waiting {delay:.2f} seconds before next attempt"
    error_during_attempt: "Error during attempt {attempt}: {error}"
    error_max_retries: "Reached maximum retries ({max_retries}). Stopping due to error."
    waiting_after_error: "Waiting {delay:.2f} seconds before retrying after error"
    completed_retry: "Completed agent_track_submit_with_retry after {attempts} attempts"

# Browser cleanup and monitoring settings
cleanup:
  enabled: false            # Set true if you want automatic cleanup after inactivity
  inactivity_timeout:
    hours: 1
    minutes: 30
  grace_period_minutes: 5   # Wait after automation finishes before monitoring starts
  check_interval_sec: 30    # Interval between browser activity checks

# Prompts to try for the challenge
prompts:
  - file: "prompts/prompt.txt"
    # Single prompt file used by the script